extends: airbnb-base
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      extensions:
        - .ts
rules:
  import/extensions: off
  '@typescript-eslint/no-unused-vars': error
overrides:
  files: ["src/**/*.test.ts"]
  env:
    jest: true
